// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0Rf2WRhLNtCGdgBAc38wxwUlkuFeR8Q',
    appId: '1:598217463439:web:7d8317822fd842a8cf02fa',
    messagingSenderId: '598217463439',
    projectId: 'barber-986c1',
    authDomain: 'barber-986c1.firebaseapp.com',
    storageBucket: 'barber-986c1.firebasestorage.app',
    measurementId: 'G-QST0MCQYGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKTu4XHiBNbORYQG-WmV6gaZxx1IBz3lY',
    appId: '1:598217463439:android:152592c7643c7a61cf02fa',
    messagingSenderId: '598217463439',
    projectId: 'barber-986c1',
    storageBucket: 'barber-986c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnKuX1Qey9NFYZVsGgCCwVJiiYC9AHLL8',
    appId: '1:598217463439:ios:913297f52f1b3adbcf02fa',
    messagingSenderId: '598217463439',
    projectId: 'barber-986c1',
    storageBucket: 'barber-986c1.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnKuX1Qey9NFYZVsGgCCwVJiiYC9AHLL8',
    appId: '1:598217463439:ios:913297f52f1b3adbcf02fa',
    messagingSenderId: '598217463439',
    projectId: 'barber-986c1',
    storageBucket: 'barber-986c1.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR0Rf2WRhLNtCGdgBAc38wxwUlkuFeR8Q',
    appId: '1:598217463439:web:bc213c025f3b9995cf02fa',
    messagingSenderId: '598217463439',
    projectId: 'barber-986c1',
    authDomain: 'barber-986c1.firebaseapp.com',
    storageBucket: 'barber-986c1.firebasestorage.app',
    measurementId: 'G-Q0E3YH4SFP',
  );
}
